-- VHDL Entity alien_game_lib.alien_game_top_level.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop5.tuni.fi)
--          at - 11:26:46 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_game_top_level IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      your_signals   : OUT    std_logic
   );

-- Declarations

END alien_game_top_level ;

--
-- VHDL Architecture alien_game_lib.alien_game_top_level.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop5.tuni.fi)
--          at - 11:26:45 12/04/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY pre_made;

ARCHITECTURE struct OF alien_game_top_level IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color      : std_logic_vector(23 DOWNTO 0);
   SIGNAL frame_done : std_logic;
   SIGNAL w_rdy      : std_logic;
   SIGNAL write      : std_logic;
   SIGNAL x_coord    : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord    : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT game_logic_hierarcical_block
   PORT (
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic ;
      rst_n       : IN     std_logic ;
      write_ready : IN     std_logic ;
      color       : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done  : OUT    std_logic ;
      write       : OUT    std_logic ;
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT z_black_box_y
   PORT (
      clk            : IN     std_logic;
      color_BGR      : IN     std_logic_vector (23 DOWNTO 0);
      frame_done     : IN     std_logic;
      rst_n          : IN     std_logic;
      write          : IN     std_logic;
      x_coord        : IN     std_logic_vector (7 DOWNTO 0);
      y_coord        : IN     std_logic_vector (7 DOWNTO 0);
      if_you_name    : OUT    std_logic_vector (7 DOWNTO 0);
      iotre_will     : OUT    std_logic;
      like_this      : OUT    std_logic;
      of_this_course : OUT    std_logic;
      throw_you_out  : OUT    std_logic;
      w_rdy          : OUT    std_logic;
      your_signals   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : game_logic_hierarcical_block USE ENTITY alien_game_lib.game_logic_hierarcical_block;
   FOR ALL : z_black_box_y USE ENTITY pre_made.z_black_box_y;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : game_logic_hierarcical_block
      PORT MAP (
         btn         => btn,
         clk         => clk,
         rst_n       => rst_n,
         write_ready => w_rdy,
         color       => color,
         frame_done  => frame_done,
         write       => write,
         x_coord     => x_coord,
         y_coord     => y_coord
      );
   U_0 : z_black_box_y
      PORT MAP (
         clk            => clk,
         color_BGR      => color,
         frame_done     => frame_done,
         rst_n          => rst_n,
         write          => write,
         x_coord        => x_coord,
         y_coord        => y_coord,
         if_you_name    => if_you_name,
         iotre_will     => iotre_will,
         like_this      => like_this,
         of_this_course => of_this_course,
         throw_you_out  => throw_you_out,
         w_rdy          => w_rdy,
         your_signals   => your_signals
      );

END struct;
