-- VHDL Entity alien_game_lib.bonus_t2_serial_data_transmit.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop14.tuni.fi)
--          at - 10:20:21 12/01/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY bonus_t2_serial_data_transmit IS
   PORT( 
      bit_in   : IN     std_logic;
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      transmit : IN     std_logic;
      ready    : OUT    std_logic;
      s_clk    : OUT    std_logic;
      s_sda    : OUT    std_logic
   );

-- Declarations

END bonus_t2_serial_data_transmit ;

--
-- VHDL Architecture alien_game_lib.bonus_t2_serial_data_transmit.fsm
--
-- Created:
--          by - viuhom.viuhom (linux-desktop14.tuni.fi)
--          at - 10:20:21 12/01/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF bonus_t2_serial_data_transmit IS

   TYPE STATE_TYPE IS (
      idle,
      trasnmit1,
      transmit2
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_trasnmit1 : std_logic;
   SIGNAL csm_to_transmit2 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= idle;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_trasnmit1 <= '0';
      csm_to_transmit2 <= '0';
      CASE current_state IS
         WHEN idle => 
            IF (transmit = '1') THEN 
               next_state <= trasnmit1;
               csm_to_trasnmit1 <= '1';
            ELSE
               next_state <= idle;
            END IF;
         WHEN trasnmit1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= transmit2;
               csm_to_transmit2 <= '1';
            ELSE
               next_state <= trasnmit1;
            END IF;
         WHEN transmit2 => 
            IF (csm_timeout = '1') THEN 
               next_state <= idle;
            ELSE
               next_state <= transmit2;
            END IF;
         WHEN OTHERS =>
            next_state <= idle;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      bit_in,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      ready <= '1';
      s_clk <= '0';
      s_sda <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN trasnmit1 => 
            ready <= '0';
            s_sda <= bit_in;
            s_clk <= '1';
         WHEN transmit2 => 
            s_clk <= '0';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_trasnmit1,
      csm_to_transmit2
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_trasnmit1 = '1') THEN
         csm_next_timer <= "10"; -- no cycles(3)-1=2
      ELSIF (csm_to_transmit2 = '1') THEN
         csm_next_timer <= "10"; -- no cycles(3)-1=2
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
