-- VHDL Entity alien_game_lib.button_block.interface
--
-- Created:
--          by - viuhom.viuhom (linux-desktop6.tuni.fi)
--          at - 12:23:55 10/07/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY button_block IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      enable    : IN     std_logic;
      btn_pulse : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END button_block ;

--
-- VHDL Architecture alien_game_lib.button_block.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop6.tuni.fi)
--          at - 12:23:54 10/07/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF button_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout1 : std_logic_vector(3 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout1 <= "0000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout1, btn, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => btn_pulse <= dout1;
      WHEN '1' => btn_pulse <= btn;
      WHEN OTHERS => btn_pulse <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
