-- VHDL Entity alien_game_lib.c1_t3_decrementer.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop12.tuni.fi)
--          at - 12:13:00 09/16/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3_decrementer IS
   PORT( 
      dec_value  : IN     std_logic_vector (2 DOWNTO 0);
      dec_result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_t3_decrementer ;

--
-- VHDL Architecture alien_game_lib.c1_t3_decrementer.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop12.tuni.fi)
--          at - 12:13:00 09/16/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_t3_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic_vector(2 DOWNTO 0);
   SIGNAL result : std_logic_vector(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT c1_t2_incrementer
   PORT (
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t2_incrementer USE ENTITY alien_game_lib.c1_t2_incrementer;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'inv'
   dout <= NOT(dec_value);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inv'
   dec_result <= NOT(result);

   -- Instance port mappings.
   U_0 : c1_t2_incrementer
      PORT MAP (
         value  => dout,
         result => result
      );

END struct;
