-- VHDL Entity alien_game_lib.c2_t6_basic_alien_design_top.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop2.tuni.fi)
--          at - 10:54:48 11/24/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t6_basic_alien_design_top IS
   PORT( 
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      X_coord        : OUT    std_logic_vector (7 DOWNTO 0);
      Y_coord        : OUT    std_logic_vector (7 DOWNTO 0);
      alien_defeated : OUT    std_logic;
      color          : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c2_t6_basic_alien_design_top ;

--
-- VHDL Architecture alien_game_lib.c2_t6_basic_alien_design_top.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop2.tuni.fi)
--          at - 10:54:48 11/24/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t6_basic_alien_design_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL direction : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL X_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t6_alien_hitblock
   PORT (
      clk            : IN     std_logic ;
      hit            : IN     std_logic ;
      rst            : IN     std_logic ;
      alien_defeated : OUT    std_logic ;
      color          : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t6_basic_alien_coordinate_block
   PORT (
      clk       : IN     std_logic ;
      direction : IN     std_logic ;
      enable    : IN     std_logic ;
      rst_n     : IN     std_logic ;
      X_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t6_direction_block
   PORT (
      X_coord   : IN     std_logic_vector (7 DOWNTO 0);
      clk       : IN     std_logic ;
      enable    : IN     std_logic ;
      rst       : IN     std_logic ;
      direction : INOUT  std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t6_alien_hitblock USE ENTITY alien_game_lib.c2_t6_alien_hitblock;
   FOR ALL : c2_t6_basic_alien_coordinate_block USE ENTITY alien_game_lib.c2_t6_basic_alien_coordinate_block;
   FOR ALL : c2_t6_direction_block USE ENTITY alien_game_lib.c2_t6_direction_block;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   Y_coord <= "00000001";

   -- Instance port mappings.
   U_3 : c2_t6_alien_hitblock
      PORT MAP (
         clk            => clk,
         hit            => hit,
         rst            => rst_n,
         alien_defeated => alien_defeated,
         color          => color
      );
   U_0 : c2_t6_basic_alien_coordinate_block
      PORT MAP (
         clk       => clk,
         direction => direction,
         enable    => enable,
         rst_n     => rst_n,
         X_coord   => X_coord_internal
      );
   U_1 : c2_t6_direction_block
      PORT MAP (
         X_coord   => X_coord_internal,
         clk       => clk,
         enable    => enable,
         rst       => rst_n,
         direction => direction
      );

   -- Implicit buffered output assignments
   X_coord <= X_coord_internal;

END struct;
