-- VHDL Entity alien_game_lib.c2_t1_a_hello_led_simulation.symbol
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 10:54:40 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_a_hello_led_simulation IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_a_hello_led_simulation ;

--
-- VHDL Architecture alien_game_lib.c2_t1_a_hello_led_simulation.struct
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 10:54:40 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_a_hello_led_simulation IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   y_coord <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   x_coord <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   color_BGR <= "000001110000000000000000";

   -- Instance port mappings.

END struct;
