-- VHDL Entity alien_game_lib.c2_t1_c_combined_hello_LED.symbol
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 11:58:09 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_c_combined_hello_LED IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw0       : IN     std_logic;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_c_combined_hello_LED ;

--
-- VHDL Architecture alien_game_lib.c2_t1_c_combined_hello_LED.struct
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 11:58:09 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t1_c_combined_hello_LED IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din5 : std_logic_vector(23 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t1_a_hello_led_simulation
   PORT (
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t1_b_interactive_effect_on_LED
   PORT (
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t1_a_hello_led_simulation USE ENTITY alien_game_lib.c2_t1_a_hello_led_simulation;
   FOR ALL : c2_t1_b_interactive_effect_on_LED USE ENTITY alien_game_lib.c2_t1_b_interactive_effect_on_LED;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(din2, din5, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => color_BGR <= din2;
      WHEN '1' => color_BGR <= din5;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(din1, din4, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => y_coord <= din1;
      WHEN '1' => y_coord <= din4;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(din0, din3, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => x_coord <= din0;
      WHEN '1' => x_coord <= din3;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_0 : c2_t1_a_hello_led_simulation
      PORT MAP (
         color_BGR => din2,
         x_coord   => din0,
         y_coord   => din1
      );
   U_1 : c2_t1_b_interactive_effect_on_LED
      PORT MAP (
         btn       => btn,
         color_BGR => din5,
         x_coord   => din3,
         y_coord   => din4
      );

END struct;
