-- VHDL Entity alien_game_lib.c2_t1_b_interactive_effect_on_LED.symbol
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 11:32:10 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_b_interactive_effect_on_LED IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_b_interactive_effect_on_LED ;

--
-- VHDL Architecture alien_game_lib.c2_t1_b_interactive_effect_on_LED.struct
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 11:32:10 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_b_interactive_effect_on_LED IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout : std_logic_vector(23 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   din0 <= "101100001000101011000111";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout <= "111111100000111000010001";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   din2 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   din1 <= "00001010";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   din3 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din4 <= "00001010";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(din0, dout, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => color_BGR <= din0;
      WHEN '1' => color_BGR <= dout;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(din2, din1, btn)
   BEGIN
      CASE btn(1) IS
      WHEN '0' => x_coord <= din2;
      WHEN '1' => x_coord <= din1;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(din3, din4, btn)
   BEGIN
      CASE btn(2) IS
      WHEN '0' => y_coord <= din3;
      WHEN '1' => y_coord <= din4;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.

END struct;
