-- VHDL Entity alien_game_lib.c3_t2_Bullet_Flight_Modelling.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop6.tuni.fi)
--          at - 11:14:13 10/09/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t2_Bullet_Flight_Modelling IS
   PORT( 
      Gun_X_coordinate    : IN     std_logic_vector (7 DOWNTO 0);
      btn                 : IN     std_logic_vector (3 DOWNTO 0);
      clk                 : IN     std_logic;
      enable              : IN     std_logic;
      rst_n               : IN     std_logic;
      Bullet_X_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      Bullet_Y_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      Color               : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c3_t2_Bullet_Flight_Modelling ;

--
-- VHDL Architecture alien_game_lib.c3_t2_Bullet_Flight_Modelling.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop6.tuni.fi)
--          at - 11:14:12 10/09/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t2_Bullet_Flight_Modelling IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL btn_pulse : std_logic;
   SIGNAL data_out  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3     : std_logic_vector(1 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL Bullet_X_coordinate_internal : std_logic_vector (7 DOWNTO 0);
   SIGNAL Bullet_Y_coordinate_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t4_right_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t2_button_block
   PORT (
      Bullet_Y_coordinate : IN     std_logic_vector (7 DOWNTO 0);
      btn                 : IN     std_logic_vector (3 DOWNTO 0);
      enable              : IN     std_logic ;
      btn_pulse           : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t4_right_shifter USE ENTITY alien_game_lib.c2_t4_right_shifter;
   FOR ALL : c3_t2_button_block USE ENTITY alien_game_lib.c3_t2_button_block;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   Bullet_X_coordinate_internal <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   Bullet_Y_coordinate_internal <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= dout2;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout1 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   Color <= "000101010111000111000111";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'merge'
   dout3 <= enable & btn_pulse;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(Bullet_X_coordinate_internal, Gun_X_coordinate, 
                          btn_pulse)
   BEGIN
      CASE btn_pulse IS
      WHEN '0' => dout <= Bullet_X_coordinate_internal;
      WHEN '1' => dout <= Gun_X_coordinate;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(Bullet_Y_coordinate_internal, data_out, dout1, 
                          dout3)
   BEGIN
      CASE dout3 IS
      WHEN "00" => dout2 <= Bullet_Y_coordinate_internal;
      WHEN "01" => dout2 <= Bullet_Y_coordinate_internal;
      WHEN "10" => dout2 <= data_out;
      WHEN "11" => dout2 <= dout1;
      WHEN OTHERS => dout2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_5 : c2_t4_right_shifter
      PORT MAP (
         data_in  => Bullet_Y_coordinate_internal,
         data_out => data_out
      );
   U_0 : c3_t2_button_block
      PORT MAP (
         Bullet_Y_coordinate => Bullet_Y_coordinate_internal,
         btn                 => btn,
         enable              => enable,
         btn_pulse           => btn_pulse
      );

   -- Implicit buffered output assignments
   Bullet_X_coordinate <= Bullet_X_coordinate_internal;
   Bullet_Y_coordinate <= Bullet_Y_coordinate_internal;

END struct;
