-- VHDL Entity alien_game_lib.c5_t1_hit_detector.symbol
--
-- Created:
--          by - viuhom.viuhom (linux-desktop5.tuni.fi)
--          at - 11:26:33 11/10/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_hit_detector IS
   PORT( 
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      hit            : OUT    std_logic
   );

-- Declarations

END c5_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c5_t1_hit_detector.struct
--
-- Created:
--          by - viuhom.viuhom (linux-desktop5.tuni.fi)
--          at - 11:26:33 11/10/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c5_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1   : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout11 : std_logic;
   SIGNAL dout12 : std_logic;
   SIGNAL dout13 : std_logic;
   SIGNAL dout14 : std_logic;
   SIGNAL dout15 : std_logic;
   SIGNAL dout16 : std_logic;
   SIGNAL dout17 : std_logic;
   SIGNAL dout18 : std_logic;
   SIGNAL dout19 : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout20 : std_logic;
   SIGNAL dout21 : std_logic;
   SIGNAL dout22 : std_logic;
   SIGNAL dout23 : std_logic;
   SIGNAL dout24 : std_logic;
   SIGNAL dout25 : std_logic;
   SIGNAL dout26 : std_logic;
   SIGNAL dout27 : std_logic;
   SIGNAL dout28 : std_logic;
   SIGNAL dout29 : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout30 : std_logic;
   SIGNAL dout31 : std_logic;
   SIGNAL dout32 : std_logic;
   SIGNAL dout33 : std_logic;
   SIGNAL dout34 : std_logic;
   SIGNAL dout35 : std_logic;
   SIGNAL dout36 : std_logic;
   SIGNAL dout37 : std_logic;
   SIGNAL dout38 : std_logic;
   SIGNAL dout39 : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout40 : std_logic;
   SIGNAL dout41 : std_logic;
   SIGNAL dout42 : std_logic;
   SIGNAL dout43 : std_logic;
   SIGNAL dout44 : std_logic;
   SIGNAL dout45 : std_logic;
   SIGNAL dout46 : std_logic;
   SIGNAL dout47 : std_logic;
   SIGNAL dout48 : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;
   SIGNAL qb     : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'split'
   SIGNAL mw_U_2temp_din : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_11' of 'split'
   SIGNAL mw_U_11temp_din : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_12' of 'split'
   SIGNAL mw_U_12temp_din : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_15' of 'adff'
   qb <= NOT(mw_U_15reg_cval);
   u_15seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_15reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_15reg_cval <= dout27;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout <= dout0 AND dout1;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout16 <= dout2 AND dout3;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout17 <= dout4 AND dout5;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout18 <= dout6 AND dout7;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout19 <= dout8 AND dout12;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout20 <= dout9 AND dout13;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout21 <= dout10 AND dout14;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   dout22 <= dout11 AND dout15;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout25 <= dout23 AND dout24;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout27 <= dout26 AND din1;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'and'
   dout43 <= dout35 AND dout31;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   hit <= dout27 AND qb;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'and'
   dout45 <= dout36 AND dout32;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'and'
   dout48 <= dout37 AND dout33;

   -- ModuleWare code(v1.12) for instance 'U_20' of 'and'
   dout47 <= dout38 AND dout34;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'and'
   dout46 <= dout39 AND dout30;

   -- ModuleWare code(v1.12) for instance 'U_22' of 'and'
   dout44 <= dout40 AND dout29;

   -- ModuleWare code(v1.12) for instance 'U_23' of 'and'
   dout42 <= dout41 AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'or'
   dout26 <= dout OR dout16 OR dout17 OR dout18 OR dout19 OR dout20
             OR dout21 OR dout22;

   -- ModuleWare code(v1.12) for instance 'U_24' of 'or'
   din1 <= dout25 OR dout43 OR dout45 OR dout48 OR dout47 OR dout46
           OR dout44 OR dout42;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= bullet_x_coord;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(7 DOWNTO 0);
      dout0 <= temp_din(0);
      dout2 <= temp_din(1);
      dout4 <= temp_din(2);
      dout6 <= temp_din(3);
      dout8 <= temp_din(4);
      dout9 <= temp_din(5);
      dout10 <= temp_din(6);
      dout11 <= temp_din(7);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'split'
   mw_U_2temp_din <= alien_x_coord;
   u_2combo_proc: PROCESS (mw_U_2temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_2temp_din(7 DOWNTO 0);
      dout1 <= temp_din(0);
      dout3 <= temp_din(1);
      dout5 <= temp_din(2);
      dout7 <= temp_din(3);
      dout12 <= temp_din(4);
      dout13 <= temp_din(5);
      dout14 <= temp_din(6);
      dout15 <= temp_din(7);
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'split'
   mw_U_11temp_din <= alien_y_coord;
   u_11combo_proc: PROCESS (mw_U_11temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_11temp_din(7 DOWNTO 0);
      dout23 <= temp_din(0);
      dout35 <= temp_din(1);
      dout36 <= temp_din(2);
      dout37 <= temp_din(3);
      dout38 <= temp_din(4);
      dout39 <= temp_din(5);
      dout40 <= temp_din(6);
      dout41 <= temp_din(7);
   END PROCESS u_11combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'split'
   mw_U_12temp_din <= bullet_y_coord;
   u_12combo_proc: PROCESS (mw_U_12temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_12temp_din(7 DOWNTO 0);
      dout24 <= temp_din(0);
      dout31 <= temp_din(1);
      dout32 <= temp_din(2);
      dout33 <= temp_din(3);
      dout34 <= temp_din(4);
      dout30 <= temp_din(5);
      dout29 <= temp_din(6);
      dout28 <= temp_din(7);
   END PROCESS u_12combo_proc;

   -- Instance port mappings.

END struct;
