## 50MHz clk
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS18} [get_ports clk]
create_clock -period 20.000 -name clk_pin -waveform {0.000 10.000} -add [get_ports clk]

set_property PACKAGE_PIN R17 [get_ports {if_you_name[3]}]
set_property PACKAGE_PIN D19 [get_ports {btn[0]}]
set_property PACKAGE_PIN Y11 [get_ports of_this_course]
set_property PACKAGE_PIN D20 [get_ports {btn[1]}]
set_property PACKAGE_PIN R16 [get_ports like_this]
set_property PACKAGE_PIN L19 [get_ports {btn[3]}]
set_property PACKAGE_PIN P18 [get_ports {if_you_name[4]}]
set_property PACKAGE_PIN V15 [get_ports {if_you_name[7]}]
set_property PACKAGE_PIN V18 [get_ports {if_you_name[1]}]
set_property PACKAGE_PIN U17 [get_ports your_signals]
set_property PACKAGE_PIN Y12 [get_ports throw_you_out]
set_property PACKAGE_PIN V13 [get_ports {if_you_name[6]}]
set_property PACKAGE_PIN W11 [get_ports iotre_will]
set_property PACKAGE_PIN M14 [get_ports {led[3]}]
set_property PACKAGE_PIN N16 [get_ports {led[2]}]
set_property PACKAGE_PIN T16 [get_ports {if_you_name[2]}]
set_property PACKAGE_PIN L20 [get_ports {btn[2]}]
set_property PACKAGE_PIN V17 [get_ports {if_you_name[0]}]
set_property PACKAGE_PIN M19 [get_ports rst_n]
set_property PACKAGE_PIN R14 [get_ports {led[0]}]
set_property PACKAGE_PIN N17 [get_ports {if_you_name[5]}]
set_property PACKAGE_PIN P14 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports of_this_course]
set_property IOSTANDARD LVCMOS18 [get_ports your_signals]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports iotre_will]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports throw_you_out]
set_property IOSTANDARD LVCMOS18 [get_ports {if_you_name[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports like_this]

## sw0
set_property IOSTANDARD LVCMOS18 [get_ports sw0]
set_property PACKAGE_PIN M20 [get_ports sw0]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U_1/Bullet_Y_coordinate[0]} {U_1/Bullet_Y_coordinate[1]} {U_1/Bullet_Y_coordinate[2]} {U_1/Bullet_Y_coordinate[3]} {U_1/Bullet_Y_coordinate[4]} {U_1/Bullet_Y_coordinate[5]} {U_1/Bullet_Y_coordinate[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {U_1/X_coord1[0]} {U_1/X_coord1[1]} {U_1/X_coord1[2]} {U_1/X_coord1[3]} {U_1/X_coord1[4]} {U_1/X_coord1[5]} {U_1/X_coord1[6]} {U_1/X_coord1[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {U_1/X_coordinate[0]} {U_1/X_coordinate[1]} {U_1/X_coordinate[2]} {U_1/X_coordinate[3]} {U_1/X_coordinate[4]} {U_1/X_coordinate[5]} {U_1/X_coordinate[6]} {U_1/X_coordinate[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {btn_IBUF[0]} {btn_IBUF[1]} {btn_IBUF[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list frame_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list write]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list U_1/alien_defeated]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
