-- VHDL Entity tb_lib.tb_pixel_io.symbol
--
-- Created:
--          by - kayra.UNKNOWN (linux-desktop8.tuni.fi)
--          at - 10:32:45 07/03/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_pixel_io IS
-- Declarations

END tb_pixel_io ;

--
-- VHDL Architecture tb_lib.tb_pixel_io.struct
--
-- Created:
--          by - laurila2.laurila2 (linux-desktop8.tuni.fi)
--          at - 11:55:39 09/25/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_pixel_io IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL btn   : std_logic_vector(3 DOWNTO 0);
   SIGNAL color : std_logic_vector(23 DOWNTO 0);
   SIGNAL sw0   : std_logic;
   SIGNAL x     : std_logic_vector(7 DOWNTO 0);
   SIGNAL y     : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t1_c_combined_hello_LED
   PORT (
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw0       : IN     std_logic ;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT pixel_io_tester
   PORT (
      color : IN     std_logic_vector (23 DOWNTO 0);
      x     : IN     std_logic_vector (7 DOWNTO 0);
      y     : IN     std_logic_vector (7 DOWNTO 0);
      btn   : OUT    std_logic_vector (3 DOWNTO 0);
      sw0   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t1_c_combined_hello_LED USE ENTITY alien_game_lib.c2_t1_c_combined_hello_LED;
   FOR ALL : pixel_io_tester USE ENTITY tb_lib.pixel_io_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : c2_t1_c_combined_hello_LED
      PORT MAP (
         btn       => btn,
         sw0       => sw0,
         color_BGR => color,
         x_coord   => x,
         y_coord   => y
      );
   U_0 : pixel_io_tester
      PORT MAP (
         color => color,
         x     => x,
         y     => y,
         btn   => btn,
         sw0   => sw0
      );

END struct;
